### ISSUE TITLE
Makie todo list

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/GGplot.jl#5]
changing central longitude
    contour labels
    colors following WOCE Pantone suggestions (WOCE Atlas)
    how to give a choice between CairoMakie, GLMakie

@ggebbie
Owner Author
[ggebbie](https://github.com/ggebbie) commented [on May 6](https://github.com/ggebbie/TMI.jl/issues/79#issuecomment-1119536759)

 See makie branch on github.com/ggebbie/TMI.jl

- [ ]    try repeating one meridian on each side of the wraparound
- [ ]     try solid continents
- [ ]     try mapping solid background color (to eliminate edge artifacts)
- [ ]     search for GeoMakie scale factors when initializing
- [ ]  changing central longitude
- [ ] contour labels
- [ ] colors following WOCE Pantone suggestions (WOCE Atlas)
- [ ] how to give a choice between CairoMakie, GLMakie

**Comment by ggebbie** [comment]
This repository's scope has been narrowed to deal with plots that use Python. The name should be changed to reflect this change, such as `OceanPythonPlot`. Details related to Makie would involve major changes to the code and are better done elsewhere.
